FROM registry.d/php-v

ENV K8S_VERSION=1.21.2
ARG kubectl_url=http://down.load/kubectl.tar.gz
ARG telepresence_url=http://down.load/telepresence.tar.gz

RUN set -eux \
  \
  ; apt-get autoremove -y && apt-get clean -y \
  ; rm -rf /var/lib/apt/lists/* \
  ; curl -sSL ${kubectl_url} \
    | tar zxf - --strip-components=3 -C /usr/local/bin \
  ; curl -sSL ${telepresence_url} \
    | tar zxf - --strip-components=3 -C /usr/local/bin
